// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSLvdGIbgQ8b_WrhHnQQsH0zPVhEsXgpM',
    appId: '1:82288421129:web:66698a03732dd6487d0bd8',
    messagingSenderId: '82288421129',
    projectId: 'auth-autofeed',
    authDomain: 'auth-autofeed.firebaseapp.com',
    storageBucket: 'auth-autofeed.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVYlD2YitXeh5DuB5GwAet2-q-_zpDEHA',
    appId: '1:82288421129:android:afd9d2d0dfd11ad77d0bd8',
    messagingSenderId: '82288421129',
    projectId: 'auth-autofeed',
    storageBucket: 'auth-autofeed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNP8352uctEt1wd3hm0l1IHhDVWdBTqCs',
    appId: '1:82288421129:ios:fe09e79116553f767d0bd8',
    messagingSenderId: '82288421129',
    projectId: 'auth-autofeed',
    storageBucket: 'auth-autofeed.firebasestorage.app',
    iosBundleId: 'com.example.autoTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNP8352uctEt1wd3hm0l1IHhDVWdBTqCs',
    appId: '1:82288421129:ios:fe09e79116553f767d0bd8',
    messagingSenderId: '82288421129',
    projectId: 'auth-autofeed',
    storageBucket: 'auth-autofeed.firebasestorage.app',
    iosBundleId: 'com.example.autoTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSLvdGIbgQ8b_WrhHnQQsH0zPVhEsXgpM',
    appId: '1:82288421129:web:e773a2e41cc7532c7d0bd8',
    messagingSenderId: '82288421129',
    projectId: 'auth-autofeed',
    authDomain: 'auth-autofeed.firebaseapp.com',
    storageBucket: 'auth-autofeed.firebasestorage.app',
  );
}
